[package]
name = "headless-streamdock-ha"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
hass-rs = "0.4.1"
image = "0.25.9"
mirajazz = "0.9.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.9.8"
